// One-shot setup: install dependencies, fetch the Playwright browser, build,
// then write bin/a11y (a wrapper with this clone's absolute path baked in)
// and symlink it into the first writable bin dir so `a11y` works from
// anywhere. Set A11Y_BIN_DIR to override where the symlink goes.
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(fileURLToPath(new URL("..", import.meta.url)));

const nodeMajor = Number(process.versions.node.split(".")[0]);
if (nodeMajor < 20) {
  console.error(`a11y setup: Node 20+ is required (you are on ${process.versions.node}).`);
  process.exit(1);
}

function run(cmd, args) {
  console.log(`\na11y setup: running ${cmd} ${args.join(" ")}`);
  const result = spawnSync(cmd, args, {
    cwd: repoRoot,
    stdio: "inherit",
    shell: process.platform === "win32",
  });
  if (result.status !== 0) {
    console.error(`a11y setup: "${cmd} ${args.join(" ")}" failed — stopping.`);
    process.exit(result.status ?? 1);
  }
}

run("npm", ["install"]);
run("npx", ["playwright", "install", "chromium"]);
run("npm", ["run", "build"]);

if (process.platform === "win32") {
  console.log("\na11y setup: build complete. The PATH wrapper is POSIX-only; on Windows run the tool as:");
  console.log(`  npm --prefix "${repoRoot}" run a11y -- quick http://localhost:8000`);
  process.exit(0);
}

const cliPath = path.join(repoRoot, "dist", "cli.js");
const wrapperPath = path.join(repoRoot, "bin", "a11y");

fs.mkdirSync(path.dirname(wrapperPath), { recursive: true });
fs.writeFileSync(
  wrapperPath,
  `#!/bin/sh\n# Generated by \`npm run setup\` — machine-specific, gitignored.\nexec node "${cliPath}" "$@"\n`,
);
fs.chmodSync(wrapperPath, 0o755);
console.log(`\na11y setup: wrote ${wrapperPath}`);

const candidates = process.env.A11Y_BIN_DIR
  ? [process.env.A11Y_BIN_DIR]
  : ["/usr/local/bin", "/opt/homebrew/bin"];

function isWritableDir(dir) {
  try {
    fs.accessSync(dir, fs.constants.W_OK);
    return fs.statSync(dir).isDirectory();
  } catch {
    return false;
  }
}

const binDir = candidates.find(isWritableDir);

if (!binDir) {
  console.log(`\na11y setup: no writable bin directory found (tried ${candidates.join(", ")}).`);
  console.log("To make the `a11y` command available everywhere, run:");
  console.log(`  sudo ln -s "${wrapperPath}" /usr/local/bin/a11y`);
  process.exit(0);
}

const linkPath = path.join(binDir, "a11y");
try {
  fs.symlinkSync(wrapperPath, linkPath);
  console.log(`\na11y setup: installed ${linkPath} -> ${wrapperPath}`);
  console.log("Try it:  a11y quick http://localhost:8000 --human");
} catch (err) {
  if (err.code !== "EEXIST") throw err;
  const existingTarget = fs.lstatSync(linkPath).isSymbolicLink()
    ? fs.readlinkSync(linkPath)
    : null;
  if (existingTarget === wrapperPath) {
    console.log(`\na11y setup: ${linkPath} is already installed — nothing to do.`);
  } else if (existingTarget) {
    console.log(`\na11y setup: ${linkPath} already exists but points at ${existingTarget} — leaving it alone.`);
    console.log(`Remove it and re-run setup if you want it pointed at this clone.`);
  } else {
    console.log(`\na11y setup: ${linkPath} already exists and isn't a symlink — leaving it alone.`);
  }
}
